platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'recicla-me' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end
