name: EAS Build

on:
  push:
    branches:
      - main  # ou a branch que você quer disparar o build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build Android (Production)
        run: eas build --platform android --profile production --non-interactive

      - name: Build iOS (Production)
        run: eas build --platform ios --profile production --non-interactive
